# AUTO-GENERATED FROM DATASET — DO NOT EDIT MANUALLY
SYMPTOM_MAP = {
    "Itching": "f_0",
    "Skin Rash": "f_1",
    "Nodal Skin Eruptions": "f_2",
    "Dischromic  Patches": "f_3",
    "Continuous Sneezing": "f_4",
    "Shivering": "f_5",
    "Chills": "f_6",
    "Watering From Eyes": "f_7",
    "Stomach Pain": "f_8",
    "Acidity": "f_9",
    "Ulcers On Tongue": "f_10",
    "Vomiting": "f_11",
    "Cough": "f_12",
    "Chest Pain": "f_13",
    "Yellowish Skin": "f_14",
    "Nausea": "f_15",
    "Loss Of Appetite": "f_16",
    "Abdominal Pain": "f_17",
    "Yellowing Of Eyes": "f_18",
    "Burning Micturition": "f_19",
    "Spotting  Urination": "f_20",
    "Passage Of Gases": "f_21",
    "Internal Itching": "f_22",
    "Indigestion": "f_23",
    "Muscle Wasting": "f_24",
    "Patches In Throat": "f_25",
    "High Fever": "f_26",
    "Extra Marital Contacts": "f_27",
    "Fatigue": "f_28",
    "Weight Loss": "f_29",
    "Restlessness": "f_30",
    "Lethargy": "f_31",
    "Irregular Sugar Level": "f_32",
    "Blurred And Distorted Vision": "f_33",
    "Obesity": "f_34",
    "Excessive Hunger": "f_35",
    "Increased Appetite": "f_36",
    "Polyuria": "f_37",
    "Sunken Eyes": "f_38",
    "Dehydration": "f_39",
    "Diarrhoea": "f_40",
    "Breathlessness": "f_41",
    "Family History": "f_42",
    "Mucoid Sputum": "f_43",
    "Headache": "f_44",
    "Dizziness": "f_45",
    "Loss Of Balance": "f_46",
    "Lack Of Concentration": "f_47",
    "Stiff Neck": "f_48",
    "Depression": "f_49",
    "Irritability": "f_50",
    "Visual Disturbances": "f_51",
    "Back Pain": "f_52",
    "Weakness In Limbs": "f_53",
    "Neck Pain": "f_54",
    "Weakness Of One Body Side": "f_55",
    "Altered Sensorium": "f_56",
    "Dark Urine": "f_57",
    "Sweating": "f_58",
    "Muscle Pain": "f_59",
    "Mild Fever": "f_60",
    "Swelled Lymph Nodes": "f_61",
    "Malaise": "f_62",
    "Red Spots Over Body": "f_63",
    "Joint Pain": "f_64",
    "Pain Behind The Eyes": "f_65",
    "Constipation": "f_66",
    "Toxic Look (Typhos)": "f_67",
    "Belly Pain": "f_68",
    "Yellow Urine": "f_69",
    "Receiving Blood Transfusion": "f_70",
    "Receiving Unsterile Injections": "f_71",
    "Coma": "f_72",
    "Stomach Bleeding": "f_73",
    "Acute Liver Failure": "f_74",
    "Swelling Of Stomach": "f_75",
    "Distention Of Abdomen": "f_76",
    "History Of Alcohol Consumption": "f_77",
    "Fluid Overload": "f_78",
    "Phlegm": "f_79",
    "Blood In Sputum": "f_80",
    "Throat Irritation": "f_81",
    "Redness Of Eyes": "f_82",
    "Sinus Pressure": "f_83",
    "Runny Nose": "f_84",
    "Congestion": "f_85",
    "Loss Of Smell": "f_86",
    "Fast Heart Rate": "f_87",
    "Rusty Sputum": "f_88",
    "Pain During Bowel Movements": "f_89",
    "Pain In Anal Region": "f_90",
    "Bloody Stool": "f_91",
    "Irritation In Anus": "f_92",
    "Cramps": "f_93",
    "Bruising": "f_94",
    "Swollen Legs": "f_95",
    "Swollen Blood Vessels": "f_96",
    "Prominent Veins On Calf": "f_97",
    "Weight Gain": "f_98",
    "Cold Hands And Feets": "f_99",
    "Mood Swings": "f_100",
    "Puffy Face And Eyes": "f_101",
    "Enlarged Thyroid": "f_102",
    "Brittle Nails": "f_103",
    "Swollen Extremeties": "f_104",
    "Abnormal Menstruation": "f_105",
    "Muscle Weakness": "f_106",
    "Anxiety": "f_107",
    "Slurred Speech": "f_108",
    "Palpitations": "f_109",
    "Drying And Tingling Lips": "f_110",
    "Knee Pain": "f_111",
    "Hip Joint Pain": "f_112",
    "Swelling Joints": "f_113",
    "Painful Walking": "f_114",
    "Movement Stiffness": "f_115",
    "Spinning Movements": "f_116",
    "Unsteadiness": "f_117",
    "Pus Filled Pimples": "f_118",
    "Blackheads": "f_119",
    "Scurring": "f_120",
    "Bladder Discomfort": "f_121",
    "Foul Smell Of Urine": "f_122",
    "Continuous Feel Of Urine": "f_123",
    "Skin Peeling": "f_124",
    "Silver Like Dusting": "f_125",
    "Small Dents In Nails": "f_126",
    "Inflammatory Nails": "f_127",
    "Blister": "f_128",
    "Red Sore Around Nose": "f_129",
    "Yellow Crust Ooze": "f_130",
    "Anxiety And Nervousness": "f_131",
    "Shortness Of Breath": "f_132",
    "Depressive Or Psychotic Symptoms": "f_133",
    "Sharp Chest Pain": "f_134",
    "Insomnia": "f_135",
    "Abnormal Involuntary Movements": "f_136",
    "Chest Tightness": "f_137",
    "Irregular Heartbeat": "f_138",
    "Breathing Fast": "f_139",
    "Hoarse Voice": "f_140",
    "Sore Throat": "f_141",
    "Difficulty Speaking": "f_142",
    "Nasal Congestion": "f_143",
    "Throat Swelling": "f_144",
    "Diminished Hearing": "f_145",
    "Lump In Throat": "f_146",
    "Throat Feels Tight": "f_147",
    "Difficulty In Swallowing": "f_148",
    "Skin Swelling": "f_149",
    "Retention Of Urine": "f_150",
    "Groin Mass": "f_151",
    "Leg Pain": "f_152",
    "Hip Pain": "f_153",
    "Suprapubic Pain": "f_154",
    "Blood In Stool": "f_155",
    "Lack Of Growth": "f_156",
    "Emotional Symptoms": "f_157",
    "Elbow Weakness": "f_158",
    "Back Weakness": "f_159",
    "Pus In Sputum": "f_160",
    "Symptoms Of The Scrotum And Testes": "f_161",
    "Swelling Of Scrotum": "f_162",
    "Pain In Testicles": "f_163",
    "Flatulence": "f_164",
    "Pus Draining From Ear": "f_165",
    "Jaundice": "f_166",
    "Mass In Scrotum": "f_167",
    "White Discharge From Eye": "f_168",
    "Irritable Infant": "f_169",
    "Abusing Alcohol": "f_170",
    "Fainting": "f_171",
    "Hostile Behavior": "f_172",
    "Drug Abuse": "f_173",
    "Sharp Abdominal Pain": "f_174",
    "Feeling Ill": "f_175",
    "Diarrhea": "f_176",
    "Vaginal Itching": "f_177",
    "Vaginal Dryness": "f_178",
    "Painful Urination": "f_179",
    "Involuntary Urination": "f_180",
    "Pain During Intercourse": "f_181",
    "Frequent Urination": "f_182",
    "Lower Abdominal Pain": "f_183",
    "Vaginal Discharge": "f_184",
    "Blood In Urine": "f_185",
    "Hot Flashes": "f_186",
    "Intermenstrual Bleeding": "f_187",
    "Hand Or Finger Pain": "f_188",
    "Wrist Pain": "f_189",
    "Hand Or Finger Swelling": "f_190",
    "Arm Pain": "f_191",
    "Wrist Swelling": "f_192",
    "Arm Stiffness Or Tightness": "f_193",
    "Arm Swelling": "f_194",
    "Hand Or Finger Stiffness Or Tightness": "f_195",
    "Wrist Stiffness Or Tightness": "f_196",
    "Lip Swelling": "f_197",
    "Toothache": "f_198",
    "Abnormal Appearing Skin": "f_199",
    "Skin Lesion": "f_200",
    "Acne Or Pimples": "f_201",
    "Dry Lips": "f_202",
    "Facial Pain": "f_203",
    "Mouth Ulcer": "f_204",
    "Skin Growth": "f_205",
    "Eye Deviation": "f_206",
    "Diminished Vision": "f_207",
    "Double Vision": "f_208",
    "Cross-Eyed": "f_209",
    "Symptoms Of Eye": "f_210",
    "Pain In Eye": "f_211",
    "Eye Moves Abnormally": "f_212",
    "Abnormal Movement Of Eyelid": "f_213",
    "Foreign Body Sensation In Eye": "f_214",
    "Irregular Appearing Scalp": "f_215",
    "Swollen Lymph Nodes": "f_216",
    "Back Pain": "f_217",
    "Neck Pain": "f_218",
    "Low Back Pain": "f_219",
    "Pain Of The Anus": "f_220",
    "Pain During Pregnancy": "f_221",
    "Pelvic Pain": "f_222",
    "Impotence": "f_223",
    "Infant Spitting Up": "f_224",
    "Vomiting Blood": "f_225",
    "Regurgitation": "f_226",
    "Burning Abdominal Pain": "f_227",
    "Symptoms Of Infants": "f_228",
    "Wheezing": "f_229",
    "Peripheral Edema": "f_230",
    "Neck Mass": "f_231",
    "Ear Pain": "f_232",
    "Jaw Swelling": "f_233",
    "Mouth Dryness": "f_234",
    "Neck Swelling": "f_235",
    "Knee Pain": "f_236",
    "Foot Or Toe Pain": "f_237",
    "Bowlegged Or Knock-Kneed": "f_238",
    "Ankle Pain": "f_239",
    "Bones Are Painful": "f_240",
    "Knee Weakness": "f_241",
    "Elbow Pain": "f_242",
    "Knee Swelling": "f_243",
    "Skin Moles": "f_244",
    "Knee Lump Or Mass": "f_245",
    "Weight Gain": "f_246",
    "Problems With Movement": "f_247",
    "Knee Stiffness Or Tightness": "f_248",
    "Leg Swelling": "f_249",
    "Foot Or Toe Swelling": "f_250",
    "Heartburn": "f_251",
    "Smoking Problems": "f_252",
    "Muscle Pain": "f_253",
    "Infant Feeding Problem": "f_254",
    "Recent Weight Loss": "f_255",
    "Problems With Shape Or Size Of Breast": "f_256",
    "Underweight": "f_257",
    "Difficulty Eating": "f_258",
    "Scanty Menstrual Flow": "f_259",
    "Vaginal Pain": "f_260",
    "Vaginal Redness": "f_261",
    "Vulvar Irritation": "f_262",
    "Weakness": "f_263",
    "Decreased Heart Rate": "f_264",
    "Increased Heart Rate": "f_265",
    "Bleeding Or Discharge From Nipple": "f_266",
    "Ringing In Ear": "f_267",
    "Plugged Feeling In Ear": "f_268",
    "Itchy Ear(S)": "f_269",
    "Frontal Headache": "f_270",
    "Fluid In Ear": "f_271",
    "Neck Stiffness Or Tightness": "f_272",
    "Spots Or Clouds In Vision": "f_273",
    "Eye Redness": "f_274",
    "Lacrimation": "f_275",
    "Itchiness Of Eye": "f_276",
    "Blindness": "f_277",
    "Eye Burns Or Stings": "f_278",
    "Itchy Eyelid": "f_279",
    "Feeling Cold": "f_280",
    "Decreased Appetite": "f_281",
    "Excessive Appetite": "f_282",
    "Excessive Anger": "f_283",
    "Loss Of Sensation": "f_284",
    "Focal Weakness": "f_285",
    "Slurring Words": "f_286",
    "Symptoms Of The Face": "f_287",
    "Disturbance Of Memory": "f_288",
    "Paresthesia": "f_289",
    "Side Pain": "f_290",
    "Fever": "f_291",
    "Shoulder Pain": "f_292",
    "Shoulder Stiffness Or Tightness": "f_293",
    "Shoulder Weakness": "f_294",
    "Arm Cramps Or Spasms": "f_295",
    "Shoulder Swelling": "f_296",
    "Tongue Lesions": "f_297",
    "Leg Cramps Or Spasms": "f_298",
    "Abnormal Appearing Tongue": "f_299",
    "Ache All Over": "f_300",
    "Lower Body Pain": "f_301",
    "Problems During Pregnancy": "f_302",
    "Spotting Or Bleeding During Pregnancy": "f_303",
    "Cramps And Spasms": "f_304",
    "Upper Abdominal Pain": "f_305",
    "Stomach Bloating": "f_306",
    "Changes In Stool Appearance": "f_307",
    "Unusual Color Or Odor To Urine": "f_308",
    "Kidney Mass": "f_309",
    "Swollen Abdomen": "f_310",
    "Symptoms Of Prostate": "f_311",
    "Leg Stiffness Or Tightness": "f_312",
    "Difficulty Breathing": "f_313",
    "Rib Pain": "f_314",
    "Joint Pain": "f_315",
    "Muscle Stiffness Or Tightness": "f_316",
    "Pallor": "f_317",
    "Hand Or Finger Lump Or Mass": "f_318",
    "Groin Pain": "f_319",
    "Abdominal Distention": "f_320",
    "Regurgitation.1": "f_321",
    "Symptoms Of The Kidneys": "f_322",
    "Melena": "f_323",
    "Flushing": "f_324",
    "Coughing Up Sputum": "f_325",
    "Seizures": "f_326",
    "Delusions Or Hallucinations": "f_327",
    "Shoulder Cramps Or Spasms": "f_328",
    "Joint Stiffness Or Tightness": "f_329",
    "Pain Or Soreness Of Breast": "f_330",
    "Excessive Urination At Night": "f_331",
    "Bleeding From Eye": "f_332",
    "Rectal Bleeding": "f_333",
    "Temper Problems": "f_334",
    "Coryza": "f_335",
    "Wrist Weakness": "f_336",
    "Eye Strain": "f_337",
    "Hemoptysis": "f_338",
    "Lymphedema": "f_339",
    "Skin On Leg Or Foot Looks Infected": "f_340",
    "Allergic Reaction": "f_341",
    "Congestion In Chest": "f_342",
    "Muscle Swelling": "f_343",
    "Pus In Urine": "f_344",
    "Abnormal Size Or Shape Of Ear": "f_345",
    "Low Back Weakness": "f_346",
    "Sleepiness": "f_347",
    "Apnea": "f_348",
    "Abnormal Breathing Sounds": "f_349",
    "Excessive Growth": "f_350",
    "Elbow Cramps Or Spasms": "f_351",
    "Feeling Hot And Cold": "f_352",
    "Blood Clots During Menstrual Periods": "f_353",
    "Absence Of Menstruation": "f_354",
    "Pulling At Ears": "f_355",
    "Gum Pain": "f_356",
    "Redness In Ear": "f_357",
    "Fluid Retention": "f_358",
    "Flu-Like Syndrome": "f_359",
    "Sinus Congestion": "f_360",
    "Painful Sinuses": "f_361",
    "Fears And Phobias": "f_362",
    "Recent Pregnancy": "f_363",
    "Uterine Contractions": "f_364",
    "Burning Chest Pain": "f_365",
    "Back Cramps Or Spasms": "f_366",
    "Stiffness All Over": "f_367",
    "Muscle Cramps, Contractures, Or Spasms": "f_368",
    "Low Back Cramps Or Spasms": "f_369",
    "Back Mass Or Lump": "f_370",
    "Nosebleed": "f_371",
    "Long Menstrual Periods": "f_372",
    "Heavy Menstrual Flow": "f_373",
    "Unpredictable Menstruation": "f_374",
    "Painful Menstruation": "f_375",
    "Infertility": "f_376",
    "Frequent Menstruation": "f_377",
    "Mass On Eyelid": "f_378",
    "Swollen Eye": "f_379",
    "Eyelid Swelling": "f_380",
    "Eyelid Lesion Or Rash": "f_381",
    "Unwanted Hair": "f_382",
    "Symptoms Of Bladder": "f_383",
    "Irregular Appearing Nails": "f_384",
    "Itching Of Skin": "f_385",
    "Hurts To Breath": "f_386",
    "Nailbiting": "f_387",
    "Skin Dryness, Peeling, Scaliness, Or Roughness": "f_388",
    "Skin On Arm Or Hand Looks Infected": "f_389",
    "Skin Irritation": "f_390",
    "Itchy Scalp": "f_391",
    "Hip Swelling": "f_392",
    "Incontinence Of Stool": "f_393",
    "Foot Or Toe Cramps Or Spasms": "f_394",
    "Warts": "f_395",
    "Bumps On Penis": "f_396",
    "Too Little Hair": "f_397",
    "Foot Or Toe Lump Or Mass": "f_398",
    "Skin Rash": "f_399",
    "Mass Or Swelling Around The Anus": "f_400",
    "Low Back Swelling": "f_401",
    "Ankle Swelling": "f_402",
    "Hip Lump Or Mass": "f_403",
    "Drainage In Throat": "f_404",
    "Dry Or Flaky Scalp": "f_405",
    "Premenstrual Tension Or Irritability": "f_406",
    "Feeling Hot": "f_407",
    "Feet Turned In": "f_408",
    "Foot Or Toe Stiffness Or Tightness": "f_409",
    "Pelvic Pressure": "f_410",
    "Elbow Swelling": "f_411",
    "Elbow Stiffness Or Tightness": "f_412",
    "Early Or Late Onset Of Menopause": "f_413",
    "Mass On Ear": "f_414",
    "Bleeding From Ear": "f_415",
    "Hand Or Finger Weakness": "f_416",
    "Low Self-Esteem": "f_417",
    "Throat Irritation": "f_418",
    "Itching Of The Anus": "f_419",
    "Swollen Or Red Tonsils": "f_420",
    "Irregular Belly Button": "f_421",
    "Swollen Tongue": "f_422",
    "Lip Sore": "f_423",
    "Vulvar Sore": "f_424",
    "Hip Stiffness Or Tightness": "f_425",
    "Mouth Pain": "f_426",
    "Arm Weakness": "f_427",
    "Leg Lump Or Mass": "f_428",
    "Disturbance Of Smell Or Taste": "f_429",
    "Discharge In Stools": "f_430",
    "Penis Pain": "f_431",
    "Loss Of Sex Drive": "f_432",
    "Obsessions And Compulsions": "f_433",
    "Antisocial Behavior": "f_434",
    "Neck Cramps Or Spasms": "f_435",
    "Pupils Unequal": "f_436",
    "Poor Circulation": "f_437",
    "Thirst": "f_438",
    "Sleepwalking": "f_439",
    "Skin Oiliness": "f_440",
    "Sneezing": "f_441",
    "Bladder Mass": "f_442",
    "Knee Cramps Or Spasms": "f_443",
    "Premature Ejaculation": "f_444",
    "Leg Weakness": "f_445",
    "Posture Problems": "f_446",
    "Bleeding In Mouth": "f_447",
    "Tongue Bleeding": "f_448",
    "Change In Skin Mole Size Or Color": "f_449",
    "Penis Redness": "f_450",
    "Penile Discharge": "f_451",
    "Shoulder Lump Or Mass": "f_452",
    "Cloudy Eye": "f_453",
    "Hysterical Behavior": "f_454",
    "Arm Lump Or Mass": "f_455",
    "Nightmares": "f_456",
    "Bleeding Gums": "f_457",
    "Pain In Gums": "f_458",
    "Bedwetting": "f_459",
    "Diaper Rash": "f_460",
    "Lump Or Mass Of Breast": "f_461",
    "Vaginal Bleeding After Menopause": "f_462",
    "Infrequent Menstruation": "f_463",
    "Mass On Vulva": "f_464",
    "Jaw Pain": "f_465",
    "Itching Of Scrotum": "f_466",
    "Postpartum Problems Of The Breast": "f_467",
    "Eyelid Retracted": "f_468",
    "Hesitancy": "f_469",
    "Elbow Lump Or Mass": "f_470",
    "Muscle Weakness": "f_471",
    "Throat Redness": "f_472",
    "Joint Swelling": "f_473",
    "Tongue Pain": "f_474",
    "Redness In Or Around Nose": "f_475",
    "Wrinkles On Skin": "f_476",
    "Foot Or Toe Weakness": "f_477",
    "Hand Or Finger Cramps Or Spasms": "f_478",
    "Back Stiffness Or Tightness": "f_479",
    "Wrist Lump Or Mass": "f_480",
    "Skin Pain": "f_481",
    "Low Back Stiffness Or Tightness": "f_482",
    "Low Urine Output": "f_483",
    "Skin On Head Or Neck Looks Infected": "f_484",
    "Stuttering Or Stammering": "f_485",
    "Problems With Orgasm": "f_486",
    "Nose Deformity": "f_487",
    "Lump Over Jaw": "f_488",
    "Sore In Nose": "f_489",
    "Hip Weakness": "f_490",
    "Back Swelling": "f_491",
    "Ankle Stiffness Or Tightness": "f_492",
    "Ankle Weakness": "f_493",
    "Neck Weakness": "f_494",
    "Inability To Walk": "f_495",
    "Fatigue.1": "f_496",
    "Fever.1": "f_497",
    "Poor Night Vision": "f_498",
    "Sore Throat.1": "f_499",
    "Clay Colored Stool": "f_500",
    "Heaviness": "f_501",
    "Painful Defecation": "f_502",
    "Bladder Insufficiency": "f_503",
    "High Fever": "f_504",
    "Dark Gums": "f_505",
    "Anal Burning": "f_506",
    "Swelling Of The Joints": "f_507",
    "Pale Spots On Skin": "f_508",
    "Tremors In Hands And Feet": "f_509",
    "Bloody Stool": "f_510",
    "Nasal Inflammation": "f_511",
    "Joint Pain.1": "f_512",
    "Coma.1": "f_513",
    "Sudden Uncontrolled Electrical Disturbances In The Brain": "f_514",
    "Swollen Tongue.1": "f_515",
    "Ear Pain.1": "f_516",
    "Blood Clot": "f_517",
    "Vomiting Blood.1": "f_518",
    "Coughing Blood": "f_519",
    "Deja Vu": "f_520",
    "Fainting.1": "f_521",
    "Abdominal Bloating": "f_522",
    "Gum Abscess": "f_523",
    "Eye Discomfort": "f_524",
    "Blisters": "f_525",
    "Hole In The Gum": "f_526",
    "Eye Pain": "f_527",
    "Cough.1": "f_528",
    "Sweating.1": "f_529",
    "Mucus In The Throat": "f_530",
    "Loss Of Consciousness": "f_531",
    "Body Pain": "f_532",
    "Headache.1": "f_533",
    "Body Getting Cold": "f_534",
    "Anxiety.1": "f_535",
    "Sensitivity To Light": "f_536",
    "Tingling In Hands And Feet": "f_537",
    "White Spots On Mouth": "f_538",
    "Loss Of Appetite": "f_539",
    "Anorexia": "f_540",
    "Tongue Ulcer": "f_541",
    "Loss Of Balance": "f_542",
    "Neck Pain.1": "f_543",
    "Difficulty Swallowing": "f_544",
    "Sleep Issues": "f_545",
    "Small Boils On The Skin": "f_546",
    "Seizures.1": "f_547",
    "Numbness": "f_548",
    "Prickly Heat Rash": "f_549",
    "Feel Cold": "f_550",
    "Insomnia.1": "f_551",
    "Slurred Speech": "f_552",
    "Bloating": "f_553",
    "Gums Swell": "f_554",
    "Abdominal Pain": "f_555",
    "Rapid Breathing": "f_556",
    "Dehydration.1": "f_557",
    "Soft Tongue": "f_558",
    "Cold": "f_559",
    "Enlarged Liver": "f_560",
    "Rashes": "f_561",
    "Frequent Urination.1": "f_562",
    "Small Nail Pits": "f_563",
    "Gingivitis": "f_564",
    "Continuous Sneezing": "f_565",
    "Mood Swings": "f_566",
    "Weight Gain.1": "f_567",
    "Fear Of The Wind": "f_568",
    "Rash": "f_569",
    "Burning Urination": "f_570",
    "Acidity.1": "f_571",
    "Watery Eyes": "f_572",
    "Diarrhea.1": "f_573",
    "Swollen": "f_574",
    "Mental Anxiety": "f_575",
    "Excessive Salivation": "f_576",
    "Double Vision.1": "f_577",
    "Pain In Hands And Feet": "f_578",
    "Pain Behind Eyes": "f_579",
    "Weakness.1": "f_580",
    "Cognitive Decline": "f_581",
    "Ear Fluid Drainage": "f_582",
    "Burning Sensation": "f_583",
    "Hard Muscle": "f_584",
    "Weight Loss": "f_585",
    "Facial Droop": "f_586",
    "Inability To Focus": "f_587",
    "Blurred Vision": "f_588",
    "Dislike Of Food": "f_589",
    "Pus Filled Pimple": "f_590",
    "Nausea.1": "f_591",
    "Talking Nonsense": "f_592",
    "Constipation.1": "f_593",
    "Family History": "f_594",
    "Paralysis": "f_595",
    "Back Pain.1": "f_596",
    "Loss Of Sense Of Smell And Taste": "f_597",
    "Sore Tongue": "f_598",
    "Pus From The Gums": "f_599",
    "Vomiting.1": "f_600",
    "Yellow Eyes": "f_601",
    "Indigestion.1": "f_602",
    "Hearing Loss": "f_603",
    "Yellow Skin": "f_604",
    "Breast Enlargement": "f_605",
    "Dry Skin": "f_606",
    "Strong Hands And Feet": "f_607",
    "Speech Difficulty": "f_608",
    "Pulse Rate Decrease": "f_609",
    "Paralysed Body": "f_610",
    "Dizziness.1": "f_611",
    "Rapid Pulse": "f_612",
    "Neck Swelling.1": "f_613",
    "Weak Joints": "f_614",
    "Muscle Weakness.1": "f_615",
    "Hearing Difficulty": "f_616",
    "Brittle Bones": "f_617",
    "Sore": "f_618",
    "Heartburn.1": "f_619",
    "Color Fading Appearance": "f_620",
    "Eye Problems": "f_621",
    "Swollen Eyelids": "f_622",
    "Chest Pain With Pressure": "f_623",
    "Excessive Bleeding": "f_624",
    "Hypertension": "f_625",
    "Abnormal Menstruation": "f_626",
    "Stiff Neck": "f_627",
    "Burning Eyes": "f_628",
    "Head Scratching": "f_629",
    "Red Eyes": "f_630",
    "Shortness Of Breath.1": "f_631",
    "Sticky Eyelids": "f_632",
    "Brittle Gums": "f_633",
    "Phlegm.1": "f_634",
    "Tooth Brittle": "f_635",
    "Temporary Distraction": "f_636",
    "Dark Colored Urine": "f_637",
    "Memory Loss": "f_638",
    "Difficulty In Defecation": "f_639",
    "Bloody Diarrhea": "f_640",
    "Chest Pain": "f_641",
    "Bones Of The Legs Curved Like Bow": "f_642",
    "Anal Pain": "f_643",
    "Coughing With Mucus": "f_644",
    "Loose Tooth": "f_645",
    "Excessive Hunger": "f_646",
    "Dry Skin.1": "f_647",
    "Swollen Ankles": "f_648",
    "Crippled": "f_649",
    "Bleeding From The Navel": "f_650",
    "Muscle Pain.1": "f_651",
    "Itching.1": "f_652",
    "Corneal Damage": "f_653",
}

CHAT_KEYWORDS = {
    "itching": "f_0",
    "skin rash": "f_1",
    "nodal skin eruptions": "f_2",
    "dischromic  patches": "f_3",
    "continuous sneezing": "f_4",
    "shivering": "f_5",
    "chills": "f_6",
    "watering from eyes": "f_7",
    "stomach pain": "f_8",
    "stomach ache": "f_8",
    "acidity": "f_9",
    "ulcers on tongue": "f_10",
    "vomiting": "f_11",
    "cough": "f_12",
    "chest pain": "f_13",
    "chest ache": "f_13",
    "yellowish skin": "f_14",
    "nausea": "f_15",
    "loss of appetite": "f_16",
    "abdominal pain": "f_17",
    "abdominal ache": "f_17",
    "yellowing of eyes": "f_18",
    "burning micturition": "f_19",
    "spotting  urination": "f_20",
    "passage of gases": "f_21",
    "internal itching": "f_22",
    "indigestion": "f_23",
    "muscle wasting": "f_24",
    "patches in throat": "f_25",
    "high fever": "f_26",
    "extra marital contacts": "f_27",
    "fatigue": "f_28",
    "weight loss": "f_29",
    "restlessness": "f_30",
    "lethargy": "f_31",
    "irregular sugar level": "f_32",
    "blurred and distorted vision": "f_33",
    "obesity": "f_34",
    "excessive hunger": "f_35",
    "increased appetite": "f_36",
    "polyuria": "f_37",
    "sunken eyes": "f_38",
    "dehydration": "f_39",
    "diarrhoea": "f_40",
    "breathlessness": "f_41",
    "family history": "f_42",
    "mucoid sputum": "f_43",
    "headache": "f_44",
    "dizziness": "f_45",
    "loss of balance": "f_46",
    "lack of concentration": "f_47",
    "stiff neck": "f_48",
    "depression": "f_49",
    "irritability": "f_50",
    "visual disturbances": "f_51",
    "back pain": "f_52",
    "back ache": "f_52",
    "weakness in limbs": "f_53",
    "neck pain": "f_54",
    "neck ache": "f_54",
    "weakness of one body side": "f_55",
    "altered sensorium": "f_56",
    "dark urine": "f_57",
    "sweating": "f_58",
    "muscle pain": "f_59",
    "muscle ache": "f_59",
    "mild fever": "f_60",
    "swelled lymph nodes": "f_61",
    "malaise": "f_62",
    "red spots over body": "f_63",
    "joint pain": "f_64",
    "joint ache": "f_64",
    "pain behind the eyes": "f_65",
    "ache behind the eyes": "f_65",
    "constipation": "f_66",
    "toxic look (typhos)": "f_67",
    "belly pain": "f_68",
    "belly ache": "f_68",
    "yellow urine": "f_69",
    "receiving blood transfusion": "f_70",
    "receiving unsterile injections": "f_71",
    "coma": "f_72",
    "stomach bleeding": "f_73",
    "acute liver failure": "f_74",
    "swelling of stomach": "f_75",
    "distention of abdomen": "f_76",
    "history of alcohol consumption": "f_77",
    "fluid overload": "f_78",
    "phlegm": "f_79",
    "blood in sputum": "f_80",
    "throat irritation": "f_81",
    "redness of eyes": "f_82",
    "sinus pressure": "f_83",
    "runny nose": "f_84",
    "congestion": "f_85",
    "loss of smell": "f_86",
    "fast heart rate": "f_87",
    "rusty sputum": "f_88",
    "pain during bowel movements": "f_89",
    "ache during bowel movements": "f_89",
    "pain in anal region": "f_90",
    "ache in anal region": "f_90",
    "bloody stool": "f_91",
    "irritation in anus": "f_92",
    "cramps": "f_93",
    "bruising": "f_94",
    "swollen legs": "f_95",
    "swollen blood vessels": "f_96",
    "prominent veins on calf": "f_97",
    "weight gain": "f_98",
    "cold hands and feets": "f_99",
    "mood swings": "f_100",
    "puffy face and eyes": "f_101",
    "enlarged thyroid": "f_102",
    "brittle nails": "f_103",
    "swollen extremeties": "f_104",
    "abnormal menstruation": "f_105",
    "muscle weakness": "f_106",
    "anxiety": "f_107",
    "slurred speech": "f_108",
    "palpitations": "f_109",
    "drying and tingling lips": "f_110",
    "knee pain": "f_111",
    "knee ache": "f_111",
    "hip joint pain": "f_112",
    "hip joint ache": "f_112",
    "swelling joints": "f_113",
    "painful walking": "f_114",
    "acheful walking": "f_114",
    "movement stiffness": "f_115",
    "spinning movements": "f_116",
    "unsteadiness": "f_117",
    "pus filled pimples": "f_118",
    "blackheads": "f_119",
    "scurring": "f_120",
    "bladder discomfort": "f_121",
    "foul smell of urine": "f_122",
    "continuous feel of urine": "f_123",
    "skin peeling": "f_124",
    "silver like dusting": "f_125",
    "small dents in nails": "f_126",
    "inflammatory nails": "f_127",
    "blister": "f_128",
    "red sore around nose": "f_129",
    "yellow crust ooze": "f_130",
    "anxiety and nervousness": "f_131",
    "shortness of breath": "f_132",
    "depressive or psychotic symptoms": "f_133",
    "sharp chest pain": "f_134",
    "sharp chest ache": "f_134",
    "insomnia": "f_135",
    "abnormal involuntary movements": "f_136",
    "chest tightness": "f_137",
    "irregular heartbeat": "f_138",
    "breathing fast": "f_139",
    "hoarse voice": "f_140",
    "sore throat": "f_141",
    "difficulty speaking": "f_142",
    "nasal congestion": "f_143",
    "throat swelling": "f_144",
    "diminished hearing": "f_145",
    "lump in throat": "f_146",
    "throat feels tight": "f_147",
    "difficulty in swallowing": "f_148",
    "skin swelling": "f_149",
    "retention of urine": "f_150",
    "groin mass": "f_151",
    "leg pain": "f_152",
    "leg ache": "f_152",
    "hip pain": "f_153",
    "hip ache": "f_153",
    "suprapubic pain": "f_154",
    "suprapubic ache": "f_154",
    "blood in stool": "f_155",
    "lack of growth": "f_156",
    "emotional symptoms": "f_157",
    "elbow weakness": "f_158",
    "back weakness": "f_159",
    "pus in sputum": "f_160",
    "symptoms of the scrotum and testes": "f_161",
    "swelling of scrotum": "f_162",
    "pain in testicles": "f_163",
    "ache in testicles": "f_163",
    "flatulence": "f_164",
    "pus draining from ear": "f_165",
    "jaundice": "f_166",
    "mass in scrotum": "f_167",
    "white discharge from eye": "f_168",
    "irritable infant": "f_169",
    "abusing alcohol": "f_170",
    "fainting": "f_171",
    "hostile behavior": "f_172",
    "drug abuse": "f_173",
    "sharp abdominal pain": "f_174",
    "sharp abdominal ache": "f_174",
    "feeling ill": "f_175",
    "diarrhea": "f_176",
    "vaginal itching": "f_177",
    "vaginal dryness": "f_178",
    "painful urination": "f_179",
    "acheful urination": "f_179",
    "involuntary urination": "f_180",
    "pain during intercourse": "f_181",
    "ache during intercourse": "f_181",
    "frequent urination": "f_182",
    "lower abdominal pain": "f_183",
    "lower abdominal ache": "f_183",
    "vaginal discharge": "f_184",
    "blood in urine": "f_185",
    "hot flashes": "f_186",
    "intermenstrual bleeding": "f_187",
    "hand or finger pain": "f_188",
    "hand or finger ache": "f_188",
    "wrist pain": "f_189",
    "wrist ache": "f_189",
    "hand or finger swelling": "f_190",
    "arm pain": "f_191",
    "arm ache": "f_191",
    "wrist swelling": "f_192",
    "arm stiffness or tightness": "f_193",
    "arm swelling": "f_194",
    "hand or finger stiffness or tightness": "f_195",
    "wrist stiffness or tightness": "f_196",
    "lip swelling": "f_197",
    "toothache": "f_198",
    "abnormal appearing skin": "f_199",
    "skin lesion": "f_200",
    "acne or pimples": "f_201",
    "dry lips": "f_202",
    "facial pain": "f_203",
    "facial ache": "f_203",
    "mouth ulcer": "f_204",
    "skin growth": "f_205",
    "eye deviation": "f_206",
    "diminished vision": "f_207",
    "double vision": "f_208",
    "cross-eyed": "f_209",
    "symptoms of eye": "f_210",
    "pain in eye": "f_211",
    "ache in eye": "f_211",
    "eye moves abnormally": "f_212",
    "abnormal movement of eyelid": "f_213",
    "foreign body sensation in eye": "f_214",
    "irregular appearing scalp": "f_215",
    "swollen lymph nodes": "f_216",
    "back pain": "f_217",
    "back ache": "f_217",
    "neck pain": "f_218",
    "neck ache": "f_218",
    "low back pain": "f_219",
    "low back ache": "f_219",
    "pain of the anus": "f_220",
    "ache of the anus": "f_220",
    "pain during pregnancy": "f_221",
    "ache during pregnancy": "f_221",
    "pelvic pain": "f_222",
    "pelvic ache": "f_222",
    "impotence": "f_223",
    "infant spitting up": "f_224",
    "vomiting blood": "f_225",
    "regurgitation": "f_226",
    "burning abdominal pain": "f_227",
    "burning abdominal ache": "f_227",
    "symptoms of infants": "f_228",
    "wheezing": "f_229",
    "peripheral edema": "f_230",
    "neck mass": "f_231",
    "ear pain": "f_232",
    "ear ache": "f_232",
    "jaw swelling": "f_233",
    "mouth dryness": "f_234",
    "neck swelling": "f_235",
    "knee pain": "f_236",
    "knee ache": "f_236",
    "foot or toe pain": "f_237",
    "foot or toe ache": "f_237",
    "bowlegged or knock-kneed": "f_238",
    "ankle pain": "f_239",
    "ankle ache": "f_239",
    "bones are painful": "f_240",
    "bones are acheful": "f_240",
    "knee weakness": "f_241",
    "elbow pain": "f_242",
    "elbow ache": "f_242",
    "knee swelling": "f_243",
    "skin moles": "f_244",
    "knee lump or mass": "f_245",
    "weight gain": "f_246",
    "problems with movement": "f_247",
    "knee stiffness or tightness": "f_248",
    "leg swelling": "f_249",
    "foot or toe swelling": "f_250",
    "heartburn": "f_251",
    "smoking problems": "f_252",
    "muscle pain": "f_253",
    "muscle ache": "f_253",
    "infant feeding problem": "f_254",
    "recent weight loss": "f_255",
    "problems with shape or size of breast": "f_256",
    "underweight": "f_257",
    "difficulty eating": "f_258",
    "scanty menstrual flow": "f_259",
    "vaginal pain": "f_260",
    "vaginal ache": "f_260",
    "vaginal redness": "f_261",
    "vulvar irritation": "f_262",
    "weakness": "f_263",
    "decreased heart rate": "f_264",
    "increased heart rate": "f_265",
    "bleeding or discharge from nipple": "f_266",
    "ringing in ear": "f_267",
    "plugged feeling in ear": "f_268",
    "itchy ear(s)": "f_269",
    "frontal headache": "f_270",
    "fluid in ear": "f_271",
    "neck stiffness or tightness": "f_272",
    "spots or clouds in vision": "f_273",
    "eye redness": "f_274",
    "lacrimation": "f_275",
    "itchiness of eye": "f_276",
    "blindness": "f_277",
    "eye burns or stings": "f_278",
    "itchy eyelid": "f_279",
    "feeling cold": "f_280",
    "decreased appetite": "f_281",
    "excessive appetite": "f_282",
    "excessive anger": "f_283",
    "loss of sensation": "f_284",
    "focal weakness": "f_285",
    "slurring words": "f_286",
    "symptoms of the face": "f_287",
    "disturbance of memory": "f_288",
    "paresthesia": "f_289",
    "side pain": "f_290",
    "side ache": "f_290",
    "fever": "f_291",
    "shoulder pain": "f_292",
    "shoulder ache": "f_292",
    "shoulder stiffness or tightness": "f_293",
    "shoulder weakness": "f_294",
    "arm cramps or spasms": "f_295",
    "shoulder swelling": "f_296",
    "tongue lesions": "f_297",
    "leg cramps or spasms": "f_298",
    "abnormal appearing tongue": "f_299",
    "ache all over": "f_300",
    "lower body pain": "f_301",
    "lower body ache": "f_301",
    "problems during pregnancy": "f_302",
    "spotting or bleeding during pregnancy": "f_303",
    "cramps and spasms": "f_304",
    "upper abdominal pain": "f_305",
    "upper abdominal ache": "f_305",
    "stomach bloating": "f_306",
    "changes in stool appearance": "f_307",
    "unusual color or odor to urine": "f_308",
    "kidney mass": "f_309",
    "swollen abdomen": "f_310",
    "symptoms of prostate": "f_311",
    "leg stiffness or tightness": "f_312",
    "difficulty breathing": "f_313",
    "rib pain": "f_314",
    "rib ache": "f_314",
    "joint pain": "f_315",
    "joint ache": "f_315",
    "muscle stiffness or tightness": "f_316",
    "pallor": "f_317",
    "hand or finger lump or mass": "f_318",
    "groin pain": "f_319",
    "groin ache": "f_319",
    "abdominal distention": "f_320",
    "regurgitation.1": "f_321",
    "symptoms of the kidneys": "f_322",
    "melena": "f_323",
    "flushing": "f_324",
    "coughing up sputum": "f_325",
    "seizures": "f_326",
    "delusions or hallucinations": "f_327",
    "shoulder cramps or spasms": "f_328",
    "joint stiffness or tightness": "f_329",
    "pain or soreness of breast": "f_330",
    "ache or soreness of breast": "f_330",
    "excessive urination at night": "f_331",
    "bleeding from eye": "f_332",
    "rectal bleeding": "f_333",
    "temper problems": "f_334",
    "coryza": "f_335",
    "wrist weakness": "f_336",
    "eye strain": "f_337",
    "hemoptysis": "f_338",
    "lymphedema": "f_339",
    "skin on leg or foot looks infected": "f_340",
    "allergic reaction": "f_341",
    "congestion in chest": "f_342",
    "muscle swelling": "f_343",
    "pus in urine": "f_344",
    "abnormal size or shape of ear": "f_345",
    "low back weakness": "f_346",
    "sleepiness": "f_347",
    "apnea": "f_348",
    "abnormal breathing sounds": "f_349",
    "excessive growth": "f_350",
    "elbow cramps or spasms": "f_351",
    "feeling hot and cold": "f_352",
    "blood clots during menstrual periods": "f_353",
    "absence of menstruation": "f_354",
    "pulling at ears": "f_355",
    "gum pain": "f_356",
    "gum ache": "f_356",
    "redness in ear": "f_357",
    "fluid retention": "f_358",
    "flu-like syndrome": "f_359",
    "sinus congestion": "f_360",
    "painful sinuses": "f_361",
    "acheful sinuses": "f_361",
    "fears and phobias": "f_362",
    "recent pregnancy": "f_363",
    "uterine contractions": "f_364",
    "burning chest pain": "f_365",
    "burning chest ache": "f_365",
    "back cramps or spasms": "f_366",
    "stiffness all over": "f_367",
    "muscle cramps, contractures, or spasms": "f_368",
    "low back cramps or spasms": "f_369",
    "back mass or lump": "f_370",
    "nosebleed": "f_371",
    "long menstrual periods": "f_372",
    "heavy menstrual flow": "f_373",
    "unpredictable menstruation": "f_374",
    "painful menstruation": "f_375",
    "acheful menstruation": "f_375",
    "infertility": "f_376",
    "frequent menstruation": "f_377",
    "mass on eyelid": "f_378",
    "swollen eye": "f_379",
    "eyelid swelling": "f_380",
    "eyelid lesion or rash": "f_381",
    "unwanted hair": "f_382",
    "symptoms of bladder": "f_383",
    "irregular appearing nails": "f_384",
    "itching of skin": "f_385",
    "hurts to breath": "f_386",
    "nailbiting": "f_387",
    "skin dryness, peeling, scaliness, or roughness": "f_388",
    "skin on arm or hand looks infected": "f_389",
    "skin irritation": "f_390",
    "itchy scalp": "f_391",
    "hip swelling": "f_392",
    "incontinence of stool": "f_393",
    "foot or toe cramps or spasms": "f_394",
    "warts": "f_395",
    "bumps on penis": "f_396",
    "too little hair": "f_397",
    "foot or toe lump or mass": "f_398",
    "skin rash": "f_399",
    "mass or swelling around the anus": "f_400",
    "low back swelling": "f_401",
    "ankle swelling": "f_402",
    "hip lump or mass": "f_403",
    "drainage in throat": "f_404",
    "dry or flaky scalp": "f_405",
    "premenstrual tension or irritability": "f_406",
    "feeling hot": "f_407",
    "feet turned in": "f_408",
    "foot or toe stiffness or tightness": "f_409",
    "pelvic pressure": "f_410",
    "elbow swelling": "f_411",
    "elbow stiffness or tightness": "f_412",
    "early or late onset of menopause": "f_413",
    "mass on ear": "f_414",
    "bleeding from ear": "f_415",
    "hand or finger weakness": "f_416",
    "low self-esteem": "f_417",
    "throat irritation": "f_418",
    "itching of the anus": "f_419",
    "swollen or red tonsils": "f_420",
    "irregular belly button": "f_421",
    "swollen tongue": "f_422",
    "lip sore": "f_423",
    "vulvar sore": "f_424",
    "hip stiffness or tightness": "f_425",
    "mouth pain": "f_426",
    "mouth ache": "f_426",
    "arm weakness": "f_427",
    "leg lump or mass": "f_428",
    "disturbance of smell or taste": "f_429",
    "discharge in stools": "f_430",
    "penis pain": "f_431",
    "penis ache": "f_431",
    "loss of sex drive": "f_432",
    "obsessions and compulsions": "f_433",
    "antisocial behavior": "f_434",
    "neck cramps or spasms": "f_435",
    "pupils unequal": "f_436",
    "poor circulation": "f_437",
    "thirst": "f_438",
    "sleepwalking": "f_439",
    "skin oiliness": "f_440",
    "sneezing": "f_441",
    "bladder mass": "f_442",
    "knee cramps or spasms": "f_443",
    "premature ejaculation": "f_444",
    "leg weakness": "f_445",
    "posture problems": "f_446",
    "bleeding in mouth": "f_447",
    "tongue bleeding": "f_448",
    "change in skin mole size or color": "f_449",
    "penis redness": "f_450",
    "penile discharge": "f_451",
    "shoulder lump or mass": "f_452",
    "cloudy eye": "f_453",
    "hysterical behavior": "f_454",
    "arm lump or mass": "f_455",
    "nightmares": "f_456",
    "bleeding gums": "f_457",
    "pain in gums": "f_458",
    "ache in gums": "f_458",
    "bedwetting": "f_459",
    "diaper rash": "f_460",
    "lump or mass of breast": "f_461",
    "vaginal bleeding after menopause": "f_462",
    "infrequent menstruation": "f_463",
    "mass on vulva": "f_464",
    "jaw pain": "f_465",
    "jaw ache": "f_465",
    "itching of scrotum": "f_466",
    "postpartum problems of the breast": "f_467",
    "eyelid retracted": "f_468",
    "hesitancy": "f_469",
    "elbow lump or mass": "f_470",
    "muscle weakness": "f_471",
    "throat redness": "f_472",
    "joint swelling": "f_473",
    "tongue pain": "f_474",
    "tongue ache": "f_474",
    "redness in or around nose": "f_475",
    "wrinkles on skin": "f_476",
    "foot or toe weakness": "f_477",
    "hand or finger cramps or spasms": "f_478",
    "back stiffness or tightness": "f_479",
    "wrist lump or mass": "f_480",
    "skin pain": "f_481",
    "skin ache": "f_481",
    "low back stiffness or tightness": "f_482",
    "low urine output": "f_483",
    "skin on head or neck looks infected": "f_484",
    "stuttering or stammering": "f_485",
    "problems with orgasm": "f_486",
    "nose deformity": "f_487",
    "lump over jaw": "f_488",
    "sore in nose": "f_489",
    "hip weakness": "f_490",
    "back swelling": "f_491",
    "ankle stiffness or tightness": "f_492",
    "ankle weakness": "f_493",
    "neck weakness": "f_494",
    "inability to walk": "f_495",
    "fatigue.1": "f_496",
    "fever.1": "f_497",
    "poor night vision": "f_498",
    "sore throat.1": "f_499",
    "clay colored stool": "f_500",
    "heaviness": "f_501",
    "painful defecation": "f_502",
    "acheful defecation": "f_502",
    "bladder insufficiency": "f_503",
    "high fever": "f_504",
    "dark gums": "f_505",
    "anal burning": "f_506",
    "swelling of the joints": "f_507",
    "pale spots on skin": "f_508",
    "tremors in hands and feet": "f_509",
    "bloody stool": "f_510",
    "nasal inflammation": "f_511",
    "joint pain.1": "f_512",
    "joint ache.1": "f_512",
    "coma.1": "f_513",
    "sudden uncontrolled electrical disturbances in the brain": "f_514",
    "swollen tongue.1": "f_515",
    "ear pain.1": "f_516",
    "ear ache.1": "f_516",
    "blood clot": "f_517",
    "vomiting blood.1": "f_518",
    "coughing blood": "f_519",
    "deja vu": "f_520",
    "fainting.1": "f_521",
    "abdominal bloating": "f_522",
    "gum abscess": "f_523",
    "eye discomfort": "f_524",
    "blisters": "f_525",
    "hole in the gum": "f_526",
    "eye pain": "f_527",
    "eye ache": "f_527",
    "cough.1": "f_528",
    "sweating.1": "f_529",
    "mucus in the throat": "f_530",
    "loss of consciousness": "f_531",
    "body pain": "f_532",
    "body ache": "f_532",
    "headache.1": "f_533",
    "body getting cold": "f_534",
    "anxiety.1": "f_535",
    "sensitivity to light": "f_536",
    "tingling in hands and feet": "f_537",
    "white spots on mouth": "f_538",
    "loss of appetite": "f_539",
    "anorexia": "f_540",
    "tongue ulcer": "f_541",
    "loss of balance": "f_542",
    "neck pain.1": "f_543",
    "neck ache.1": "f_543",
    "difficulty swallowing": "f_544",
    "sleep issues": "f_545",
    "small boils on the skin": "f_546",
    "seizures.1": "f_547",
    "numbness": "f_548",
    "prickly heat rash": "f_549",
    "feel cold": "f_550",
    "insomnia.1": "f_551",
    "slurred speech": "f_552",
    "bloating": "f_553",
    "gums swell": "f_554",
    "abdominal pain": "f_555",
    "abdominal ache": "f_555",
    "rapid breathing": "f_556",
    "dehydration.1": "f_557",
    "soft tongue": "f_558",
    "cold": "f_559",
    "enlarged liver": "f_560",
    "rashes": "f_561",
    "frequent urination.1": "f_562",
    "small nail pits": "f_563",
    "gingivitis": "f_564",
    "continuous sneezing": "f_565",
    "mood swings": "f_566",
    "weight gain.1": "f_567",
    "fear of the wind": "f_568",
    "rash": "f_569",
    "burning urination": "f_570",
    "acidity.1": "f_571",
    "watery eyes": "f_572",
    "diarrhea.1": "f_573",
    "swollen": "f_574",
    "mental anxiety": "f_575",
    "excessive salivation": "f_576",
    "double vision.1": "f_577",
    "pain in hands and feet": "f_578",
    "ache in hands and feet": "f_578",
    "pain behind eyes": "f_579",
    "ache behind eyes": "f_579",
    "weakness.1": "f_580",
    "cognitive decline": "f_581",
    "ear fluid drainage": "f_582",
    "burning sensation": "f_583",
    "hard muscle": "f_584",
    "weight loss": "f_585",
    "facial droop": "f_586",
    "inability to focus": "f_587",
    "blurred vision": "f_588",
    "dislike of food": "f_589",
    "pus filled pimple": "f_590",
    "nausea.1": "f_591",
    "talking nonsense": "f_592",
    "constipation.1": "f_593",
    "family history": "f_594",
    "paralysis": "f_595",
    "back pain.1": "f_596",
    "back ache.1": "f_596",
    "loss of sense of smell and taste": "f_597",
    "sore tongue": "f_598",
    "pus from the gums": "f_599",
    "vomiting.1": "f_600",
    "yellow eyes": "f_601",
    "indigestion.1": "f_602",
    "hearing loss": "f_603",
    "yellow skin": "f_604",
    "breast enlargement": "f_605",
    "dry skin": "f_606",
    "strong hands and feet": "f_607",
    "speech difficulty": "f_608",
    "pulse rate decrease": "f_609",
    "paralysed body": "f_610",
    "dizziness.1": "f_611",
    "rapid pulse": "f_612",
    "neck swelling.1": "f_613",
    "weak joints": "f_614",
    "muscle weakness.1": "f_615",
    "hearing difficulty": "f_616",
    "brittle bones": "f_617",
    "sore": "f_618",
    "heartburn.1": "f_619",
    "color fading appearance": "f_620",
    "eye problems": "f_621",
    "swollen eyelids": "f_622",
    "chest pain with pressure": "f_623",
    "chest ache with pressure": "f_623",
    "excessive bleeding": "f_624",
    "hypertension": "f_625",
    "abnormal menstruation": "f_626",
    "stiff neck": "f_627",
    "burning eyes": "f_628",
    "head scratching": "f_629",
    "red eyes": "f_630",
    "shortness of breath.1": "f_631",
    "sticky eyelids": "f_632",
    "brittle gums": "f_633",
    "phlegm.1": "f_634",
    "tooth brittle": "f_635",
    "temporary distraction": "f_636",
    "dark colored urine": "f_637",
    "memory loss": "f_638",
    "difficulty in defecation": "f_639",
    "bloody diarrhea": "f_640",
    "chest pain": "f_641",
    "chest ache": "f_641",
    "bones of the legs curved like bow": "f_642",
    "anal pain": "f_643",
    "anal ache": "f_643",
    "coughing with mucus": "f_644",
    "loose tooth": "f_645",
    "excessive hunger": "f_646",
    "dry skin.1": "f_647",
    "swollen ankles": "f_648",
    "crippled": "f_649",
    "bleeding from the navel": "f_650",
    "muscle pain.1": "f_651",
    "muscle ache.1": "f_651",
    "itching.1": "f_652",
    "corneal damage": "f_653",
}
